version: '2'
services:
    chat-app:
        image: chat
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://chat-mysql:3306/chat?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    chat-mysql:
        extends:
            file: mysql.yml
            service: chat-mysql
